config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  devise_for :users
  root "articles#index"
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"

  #admin page
  namespace :admin do
    resources :articles, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index, :destroy]
    root "articles#index"
  end

  resources :users

  resources :articles do
    resources :comments
  end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user # foreign key - user_id
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user

  # validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles  #связывает пользевателя с его статьями 
  has_many :comments  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def index
    status = params[:status]
    if status.nil?
      status = "public"
    end

    @articles = Article.order(:name)
    @articles = @articles.where(status: status)

    if !params[:search].nil? && params[:search] != ""
      @articles = @articles.where("lower(title) like ?", "%#{params[:search].downcase}%")
    end

    if params[:sort] == "created_at_asc"
      @articles = @articles.order("created_at ASC")
    end

    if params[:sort] == "created_at_desc"
      @articles = @articles.order("created_at DESC")
    end

    if params[:sort] == "updated_at_asc"
      @articles = @articles.order("updated_at ASC")
    end

    if params[:sort] == "updated_at_desc"
      @articles = @articles.order("updated_at DESC")
    end

    if params[:sort] == "id_desc"
      @articles = @articles.order("id DESC")
    end

    if params[:sort] == "id_asc"
      @articles = @articles.order("id ASC")
    end

    author_id = params[:author]

    if author_id
      @articles = @articles.where(user_id: author_id)
    end

    @articles = @articles.page(params[:page])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to admin_articles_path
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def index
    status = params[:status]
    if status.nil?
      status = "public"
    end

    @comments = Comment.order(:name)
    @comments = @comments.where(status: status)
    @comments = @comments.page params[:page]
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to admin_comments_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def index
    @users = User.order(:name).page params[:page]
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_users_path
  end
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def comments
  end

  def articles
  end

  def users
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index		
  end
	
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :password, :password_confirmation])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :name, :email, :password, :remember_me])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
	end	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.page(params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body, :status, :image)
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save  
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @avatar = Digest::SHA1.hexdigest(@user.id.to_s) # хэш имени аватара 
    file_path = "public/images/#{@avatar}.png" # путь к файлу аватара 
    file = File.exists?(file_path) # проверка на существование аватара 
    if file == false
      img = Avatarly.generate_avatar(@user.name, opts={size: 40})
      File.open(file_path, 'wb') do |f| 
        f.write(img)
      end
    end
  end
  
  def new
  end

end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Возвращает полный заголовок на основе заголовка страницы.
  def full_title(page_title = '')
    base_title = "Tutorial Blog"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_side.html.erb
<div class="col-2 admin-side" style="background: #f8f9fa;">
	<ul class="list-group list-group-flush admin-side_lis">
		<li class="list-group-item list-group-item-action said_admin">
        	<%=  link_to "Articles", admin_articles_path, class:"admin_list_link" %> 
		</li>
		<li class="list-group-item list-group-item-action said_admin">
        	<%=  link_to "Comments", admin_comments_path, class:"admin_list_link" %> 
		</li>
		<li class="list-group-item list-group-item-action said_admin">
        	<%=  link_to "Users", admin_users_path, class:"admin_list_link" %>
		</li>
	</ul>
</div>

app/views/admin/articles/index.html.erb
<% provide(:title, "Admin Articles") %>
<div class="row">
	<%= render "admin/side" %>
	<div class="col-9 admin-artile">
		<h3>Admin Articles</h3>
		<div class="d-flex row">
			<nav class="col-4">
				<ul class="nav nav-pills">
					<li class="nav-item">
						<%= link_to "Public",admin_articles_path(status: :public), class:"nav-link admin_tab_item_link #{'active' if params[:status] == "public" || params[:status].nil?}" %>
					</li>
					<li class="nav-item admin_tab_item">
						<%= link_to "Archived",admin_articles_path(status: :archived), class:"nav-link admin_tab_item_link #{'active' if params[:status] == "archived" }" %>
					</li>
					<li class="nav-item">
						<%= link_to "Private",admin_articles_path(status: :private), class:"nav-link admin_tab_item_link #{'active' if params[:status] == "private" }" %>
					</li>
				</ul>
			</nav>
			<div class="col-4">
				<%= link_to "created_at ASC",admin_articles_path(sort: :created_at_asc), class:"nav-link" %>
				<%= link_to "created_at DESC",admin_articles_path(sort: :created_at_desc), class:"nav-link" %>
				<%= link_to "updated_at ASC",admin_articles_path(sort: :updated_at_asc), class:"nav-link" %>
				<%= link_to "updated_at DESC",admin_articles_path(sort: :updated_at_desc), class:"nav-link" %>
				<%= link_to "ID ASC",admin_articles_path(sort: :id_asc), class:"nav-link" %>
				<%= link_to "ID DESC",admin_articles_path(sort: :id_desc), class:"nav-link" %>
			</div>
			<div class="col-4 search_wrap">
				<%= form_tag(admin_articles_path, method: :get) do %>
				<div class="d-flex">
					<%= text_field_tag "search", params[:search], placeholder: "Search article title", class:"form-control me-2" %>
					<%= hidden_field_tag "status", params[:status] %>
					<%= submit_tag "Search", class:"btn btn-outline-secondary" %>
				</div>
				<% end %>
			</div>
		</div>
		<div class="tab-content" id="nav-tabContent">
			<div class="d-flex col-12 justify-content-between admin_col_wrap">
				<p class = "col-4 admin_col_heading">
					Article title
				</p>
				<p class = "col-1 admin_col_heading">
					Article ID
				</p>
				<p class = "col-2 admin_col_heading">
					Article creator
				</p>
				<p class = "col-1 admin_col_heading">
					created at
				</p>
				<p class="col-1"></p>
			</div>
			<ul class = "list-group list-group-flush admin_list tab-pane fade active show" id="nav-public" role="tabpanel" aria-labelledby="nav-public-tab">
				<% @articles.each do |article| %>
				    	<li class = "list-group-item d-flex col-12 justify-content-between">
				        	<%= link_to article.title, article, class:"col-4 admin_list_link"%>
				        	<p class="col-1 admin_list_item">
				        		<%= article.id %>
				        	</p>
				        	<p class="col-1 admin_list_item">
				        		<%= article.user.name%>
				        	</p>
							<p class="col-1 admin_list_item">
				        		<%= article.created_at.to_s(:short) %>
				        	</p>
				        	<%=  link_to "Destroy",admin_article_path(article), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"col-1" %> 
				    	</li>
				<% end %>
			</ul>
			<%= paginate @articles %>
		</div>
	</div>
</div>

app/views/admin/comments/index.html.erb
<% provide(:title, "Admin Comments") %>
<div class="row">
	<%= render "admin/side" %>
	<div class="col-10 admin-artile">
		<h3>Admin Comments</h3>
		<div class="d-flex row">
			<nav class="col-8">
				<ul class="nav">
					<li class="nav-item">
				  		<%= link_to "Public",admin_comments_path(status: :public), class:"nav-link btn btn-outline-secondary admin_tab_item_link" %>
					</li>
					<li class="nav-item admin_tab_item">
						<%= link_to "Archived",admin_comments_path(status: :archived), class:"nav-link btn btn-outline-secondary admin_tab_item_link" %>
					</li>
					<li class="nav-item">
					<%= link_to "Private",admin_comments_path(status: :private), class:"nav-link btn btn-outline-secondary admin_tab_item_link" %>
					</li>
				</ul>
			</nav>
			<div class="col-4 search_wrap ">
				<%= form_tag(admin_comments_path, method: :get) do %>
				<div class="d-flex">
					<%= text_field_tag "search", params[:search], placeholder: "Search article title", class:"form-control me-2" %>
					<%= submit_tag "Search", class:"btn btn-outline-secondary" %>
				</div>
				<% end %>
			</div>
		</div>
		<div class="d-flex col-12 justify-content-between admin_col_wrap">
			<p class = "col-5 admin_col_heading">
				Comment body
			</p>
			<p class = "col-1 admin_col_heading">
				Comment ID
			</p>
			<p class = "col-2 admin_col_heading">
				Comment creator
			</p>
			<p class="col-1"></p>
		</div>
		<ul class = "list-group admin_list">
			<% @comments.each do |comment| %>
				<li class = "list-group-item  d-flex col-12 justify-content-between">
					<p class="col-5 admin_list_item">
						<%= comment.body %>
					</p>
					<p class="col-1 admin_list_item">
						<%= comment.id %>
					</p>
					<p class="col-1 admin_list_item">
						<%= comment.user.name %>
					</p>
					<%= link_to "Destroy", admin_comment_path(comment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"col-1" %>
				</li>
			<% end %>
		</ul>
		<%= paginate @comments %>
	</div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, "Admin Users") %>
<div class="row">
	<%= render "admin/side" %>
	<div class="col-9 admin-artile">
		<h3>Admin Users</h3>
		<div class="d-flex col-12 justify-content-between admin_col_wrap">
			<p class = "col-3 admin_col_heading">
				User name
			</p>
			<p class = "col-1 admin_col_heading">
				User ID
			</p>
			<p class = "col-2 admin_col_heading">
				User mail
			</p>
			<p class="col-1"></p>
		</div>
		<ul class = "list-group admin_list">
			<% @users.each do |user| %>
				<li class = "list-group-item  d-flex col-12 justify-content-between">
					<%= link_to user.name, user, class:"col-3 admin_list_link" %>
					<p class="col-1 admin_list_item">
						<%= user.id %>
					</p>
					<p class="col-2 admin_list_item">
						<%= user.email %>
					</p>
					<%=  link_to "Destroy",admin_user_path(user), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"col-1" %> 
				</li>
			<% end %>
		</ul>
		<%= paginate @users %>
	</div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article, html: { multipart: true } do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, class:"form-control" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.file_field :image %><br>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary", style:"margin-top:10px"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "New Article", new_article_path %>

<p>Our blog has <%= Article.public_count %> articles and counting!</p>

<ul class="list-group">
  <% @articles.each do |article| %>
    <li class="list-group-item">
      <%= link_to article.title, article, class:"list_link" %>
    </li>
  <% end %>
</ul>
<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="article">
  <h1 class="h2"><%= @article.title %></h1>

  <div>
    <%= image_tag @article.image.url(:large), class: "img" if @article.image? %>
    <p class="article_paragraph"><%= @article.body %></p>
  </div>


  <% if current_user %> <!-- проверяет авторезирован ли пользеватель  -->
    <% if @article.user_id == current_user.id %> <!-- если пользеватель авторезирован проверяет он ли сделал статью -->
      <div class="btn-group">
        <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-primary" %>
        <%= link_to "Destroy", article_path(@article), class:"btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %> 
      </div> 
    <% end %>
  <% end %>

</div>

<div class="comment">
  <h2 class="h4">Comments</h2>
  <%= render @article.comments %>

  <h2 class="h4 commennt_add">Add a comment:</h2>
  <%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <div class="articl_comments">
    <p style="font-weight: 700; font-style: italic;">
      <%= comment.user.name %>
    </p>
    <p>
      <%= comment.body %>
    </p>
      <% if current_user %> <!-- проверяет авторезирован ли пользеватель  -->
        <% if comment.user_id == current_user.id %> <!-- если пользеватель авторезирован проверяет он ли сделал коментарий -->
          <p class="comment_btn">
            <%= link_to "Destroy Comment", [comment.article, comment], class:"btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </p>
        <%end%>
      <%end%>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

  <p>
    <%= form.text_area :body, class:"form-control" %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>

  <p>
    <%= form.submit class:"btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
  <small>
    <p class="footer_text">
      Lorem ipsum dolor sit amet, consectetur adipiscing
    </p>
  </small>
    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item">
        <%= link_to "About",   about_path, class: "nav-link px-2 text-muted" %>
        </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path , class: "nav-link px-2 text-muted" %>
        </li>
        
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4">
    <%= link_to "my blog", root_path, id: "logo", class: "d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none" %>
    <nav>
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link px-2 link-secondary"%>
        </li>
        <li class="nav-item">
          <%= link_to "Help", help_path, class: "nav-link px-2 link-secondary" %>
        </li>
      </ul>
    </nav>
    <div class="col-md-3 text-end">
      <% if user_signed_in? %>

        <ul class="nav">
          <li class="nav-item">
            <%= link_to "Profile", current_user, class:"nav-link link-secondary px-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Setting', edit_user_registration_path, class: "nav-link link-secondary px-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, class: "nav-link link-secondary px-2", data: { turbo_method: :delete } %>
          </li>
        </ul>

      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary" %>
        <%= link_to "Sign-up", new_user_registration_path, class: "btn btn-primary" %>
      <%end%>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render 'layouts/shim' %>

  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluraliz(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
	<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
	<h1>Help</h1>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="col d-flex flex-column align-items-start gap-2 row align-items-center">
	<h2 class="user_header">
		<img src="/images/<%= @avatar %>.png" alt="<%=@user.name%>" class="rounded-circle">
		<%= @user.name %>
	</h2>
	<p class="text-muted"></p>
</div>